config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions:       'users/sessions'
  }

  namespace :admin do
    resources :products, :users, :categories
    get 'dashboard/index'
  end

  match 'users/index', to: 'users/users#index', via: [:get]

  resources :cart, only: [:index] do
    collection do
      get 'add_to_cart'
      get 'update_quantity_to_cart'
      get 'delete_product_to_cart'
    end
  end

    
end

app/models/category.rb
class Category < ActiveRecord::Base
	 paginates_per(20)
	 belongs_to :user
	 has_many :products
	 has_many :children, class_name: "Category",
                          foreign_key: "parent_id"
 
	 belongs_to :parent, class_name: "Category"
	 # def parent
	 # 	self.parent_id == 0 ? nil : Category.where(id: self.parent_id ).first
	 # end

	 # def children
	 # 	Category.where(parent_id: self.id )#.first
	 # end

	 def self.policy_class
	    Admin::CategoryPolicy
	 end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_authorize, only: [:show, :edit, :update, :destroy]
  def index
    authorize Category
  	@categories = Category.all.order(parent_id: :ASC).page params[:page]
  end

  def show
    
  end

  def new
  	@category = Category.new
    authorize @category
  	@categories_parent = Category.where(parent_id: "0")
  	@i = 0
  end

  def edit
  	@i = 0  	
  	@categories_parent = Category.where(parent_id: "0").order("id = #{@category.parent_id} DESC")
  end

  def create
  	@category = current_user.categories.new(category_params)
    authorize @category
  	if @category.save
      flash[:success] = "create new category success!"
  		redirect_to admin_category_path(@category)
  	else
      flash[:error] = "Fail! Please try again!"
  		render :new
  	end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Uppdate success!"
      redirect_to admin_category_path(@category)
    else
      flash[:error] = "Fail! Please try again!"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = "Uppdate success!"
    else
      flash[:error] = "Fail! Please try again!"
    end

    redirect_to admin_categories_path
  end

  private

  def check_authorize
    @category = Category.find(params[:id])
    authorize @category
  end
  def category_params
  	params.require(:category).permit(:name, :parent_id, :description, :status, :order)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def show
  	@category = Category.find(params[:id])
  	@category_children = @category.children
  	@categories_other = Category.where(:parent_id => '0', :status => "active").where.not(:id => params[:id]).order(order: :ASC)
  	
  	@products = Product.where("category_id in (?)", @category.children.map(&:id) << @category.id ).where(:status => "active")
   
  	@product_slideshow_single = Product.where(:banner => "single", :status => "active").order(sold: :DESC).limit(4)
  	@product_slideshow_double = Product.where(:banner => "double", :status => "active").order(sold: :DESC).limit(4)

  	@product_slideshow = []
  	@product_slideshow_double.each_with_index do |product, index|
  		@product_slideshow << product

  		@product_slideshow_single.each_with_index do |product2, index2|
  			if index == index2
  				@product_slideshow << product2
	  			break
	  		end
	  	end
  	end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
	def show_category_parent(id)
		@string = id.to_s
		return @string += " (none)" if id == 0
		
	  	@category = Category.find(id)		  	
		return @string += " (" + @category.name.to_s + ")" if @category.respond_to?("name")
	end

	def show_category_name(id)
		return @string += "(none)" if id == 0		
	  	@category = Category.find(id)
	  	@category.name
	end

	def find_categories_lv2(id)
		return false if id == 0
		@categories_lv2 = Category.where(:parent_id => "#{id}")
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.haml
= render "admin/shared/header"
.container	
	= form_for :category, html: {class: "form-horizontal"}, url: admin_category_path, method: :patch do |f|
		.form-group
			= f.label :name, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :name, :class => "form-control", :placeholder => "Enter category name"

		.form-group
			= f.label "Select category parent", :class => "control-label col-sm-2"
			.col-sm-10
				%select{ :name => 'category[parent_id]' }	
					- if @category.parent_id == 0
						%option{ :value => 0 } (none)

					- if @categories_parent.respond_to?("each")
						- @categories_parent.each do |category_parent|			
							%option{ :value => category_parent.id }= "#{category_parent.name}"

					- unless @category.parent_id == 0
						%option{ :value => 0 } (none)
					
					
		.form-group
			= f.label :description, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :description, :class => "form-control", :placeholder => "Enter description"
		.form-group
			= f.label :status, :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :status, "inactive", :checked => @category.status == "inactive"
					Inactive
						
				%label.radio-inline
					= f.radio_button :status, "active", :checked => @category.status == "active"
					Active

				%label.radio-inline
					= f.radio_button :status, "pending", :checked => @category.status == "pending"
					Pending					
			
				%label.radio-inline
					= f.radio_button :status, "banned", :checked => @category.status == "banned"
					Banned

		.form-group
			= f.label "Select Order", :class => "control-label col-sm-2"
			.col-sm-10
				%select{ :name => 'category[order]' }
					%option{ :value => @category.order }= "#{@category.order}"
					- 20.times do
						%option{ :value => "#{@i+=1}" }= "#{@i}"
							
		.form-group
			.col-sm-offset-2.col-sm-2
				= f.submit "Save change", :class => "btn btn-default"		
			.col-sm-6
				= link_to "Cancel", admin_categories_path, :class => "btn btn-default"

app/views/admin/categories/index.html.haml
= render "admin/shared/header"
.container
	%h1 Category#index

	.row
		.col-sm-1
			ID
		.col-sm-2
			Name	
		.col-sm-2
			Category parent
		.col-sm-1
			Order
		.col-sm-1
			Status	
		.col-sm-3 
			Description
		.col-sm-2
			= link_to "Add new category", new_admin_category_path

		- @categories.each do |category|
			.row
				.col-sm-1
					= category.id
				.col-sm-2
					= category.name
				.col-sm-2
					= show_category_parent(category.parent_id)
				.col-sm-1
					= category.order
				.col-sm-1
					= category.status
				.col-sm-3
					= category.description			
				.col-sm-2
					= link_to "Show", admin_category_path(category)
					= link_to "Edit", edit_admin_category_path(category)
					= link_to "Delete", admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"}
	= paginate @categories
	= link_to_next_page @categories, 'Next Page'
	%br
	= link_to "<< Dashboard", admin_dashboard_index_path

app/views/admin/categories/new.html.haml
= render "admin/shared/header"
.container	
	= form_for :category, html: {class: "form-horizontal"}, url: admin_categories_path, method: :post do |f|
		.form-group
			= f.label :name, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :name, :class => "form-control", :placeholder => "Enter category name"

		.form-group
			= f.label "Select category parent", :class => "control-label col-sm-2"
			.col-sm-10
				%select{ :name => 'category[parent_id]' }	
					%option{ :value => 0 } (none)
					- @categories_parent.each do |category_parent|			
						%option{ :value => category_parent.id }= "#{category_parent.name}"
					
					
		.form-group
			= f.label :description, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :description, :class => "form-control", :placeholder => "Enter description"
		.form-group
			= f.label :status, :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :status, "inactive", :checked => true
					Inactive
						
				%label.radio-inline
					= f.radio_button :status, "active", :checked => false
					Active

				%label.radio-inline
					= f.radio_button :status, "pending", :checked => false
					Pending					
			
				%label.radio-inline
					= f.radio_button :status, "banned", :checked => false
					Banned

		.form-group
			= f.label "Select Order", :class => "control-label col-sm-2"
			.col-sm-10
				%select{ :name => 'category[order]' }
					- 20.times do
						%option{ :value => "#{@i+=1}" }= "#{@i}"
							
		.form-group
			.col-sm-offset-2.col-sm-1
				= f.submit "Create", :class => "btn btn-default"		
			.col-sm-9
				= link_to "Cancel", admin_users_path, :class => "btn btn-default"

app/views/admin/categories/show.html.haml
= render "admin/shared/header"
.container
	.row
		.col-md-3
			ID
		.col-md-9
			= @category.id
	.row
		.col-md-3
			Name:
		.col-md-9
			= @category.name
	.row
		.col-md-3
			Category parent:
		.col-md-9
			= show_category_parent(@category.parent_id)
	.row
		.col-md-3
			Order:
		.col-md-9
			= @category.order
	.row
		.col-md-3
			Status:
		.col-md-9
			= @category.status
	.row
		.col-md-3
			Description:
		.col-md-9
			= @category.description
	.row
		.col-md-3
			Create by:
		.col-md-9
			= @category.user.try(:email)
	= link_to "Edit", edit_admin_category_path(@category)
	%br
	= link_to "Add new Category", new_admin_category_path
	%br
	= link_to "Back", admin_categories_path