config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions:       'users/sessions'
  }

  namespace :admin do
    resources :products, :users, :categories
    get 'dashboard/index'
  end

  match 'users/index', to: 'users/users#index', via: [:get]

  resources :cart, only: [:index] do
    collection do
      get 'add_to_cart'
      get 'update_quantity_to_cart'
      get 'delete_product_to_cart'
    end
  end

    
end

app/models/product.rb
class Product < ActiveRecord::Base
	paginates_per(20)
	mount_uploader :images, ImagesUploader
	belongs_to :user
	belongs_to :category	
	def self.policy_class
    	Admin::ProductPolicy
  	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :check_authorize, only: [:show, :update, :destroy, :edit]
  def index
    authorize Product
    @products = Product.all.page params[:page]    
  end

  def show
  end

  def new
  	@product = Product.new
    @categories_lv1 = Category.where(:parent_id => "0")
    authorize @product
  end

  def edit
  	@categories_lv1 = Category.where(parent_id: "0").order("id = #{@product.category_id} DESC")
  end

  def create
  	@product = current_user.products.new(product_params)
    authorize @product
  	if @product.save
  		flash[:notice] = "Create new product success"
  		redirect_to admin_product_path(@product)
  	else
  		flash[:danger] = "Fail!"
  		render :new
  	end
  end

  def update
  	if @product.update(product_params)
  		flash[:success] = "Update success"
  		redirect_to admin_product_path(@product)
  	else
  		flash[:danger] = "Fail!"
  		render :edit
  	end
  end

  def destroy
  	if @product.destroy
  		flash[:success] = "Deleted!"
  	else
  		flash[:danger] = "Fail!"
  	end
  	redirect_to admin_products_path
  end

  private

  def check_authorize
    @product = Product.find(params[:id])
    authorize @product  
  end

  def product_params
  	params.require(:product).permit(:name, :price, :banner, :total, :category_id, :status, :description, :sale_off, :sale_off_type, :images, :created_by)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
  	@product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
	def money_format(param)
		number_to_currency(param, unit: 'đ', delimiter: '.',precision: 0, format: '%n %u')
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.haml
= render "admin/shared/header"
.container	
	= form_for :product, html: {class: "form-horizontal"}, url: admin_product_path, method: :patch do |f|
		.form-group
			= f.label :name, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :name, :class => "form-control", :placeholder => "Enter product name"
			

		.form-group
			= f.label :images, :class => "control-label col-sm-2"
			.col-sm-10				
				= f.file_field :images, :class => "form-control"
		.form-group
			= f.label "Banner type", :class => "control-label col-sm-2"
			.col-sm-10				
				%label.radio-inline
					= f.radio_button :banner, "single", :checked => @product.banner == "single"
					single
						
				%label.radio-inline
					= f.radio_button :banner, "double", :checked => @product.banner == "double"
					double
			
		.form-group		
			= f.label :price, :class => "control-label col-sm-2"
			.col-sm-10 				
				= f.text_field :price, :class => "form-control", :placeholder => "Enter price"
			
		.form-group
			= f.label "Number of Total", :class => "control-label col-sm-2"
			.col-sm-10				
				= f.text_field :total, :class => "form-control", :placeholder => "Enter number of total"
			
		.form-group
			= f.label :category_id, :class => "control-label col-sm-2"
			.col-sm-10				
				%select{ :name => 'product[category_id]' }
					%option{ :value => @product.category_id }= "#{show_category_name(@product.category_id)}"
					-if @categories_lv1.respond_to?("each")
						- @categories_lv1.each do |category_lv1|
							%option{ :value => category_lv1.id }= "#{category_lv1.name}"	
							- if find_categories_lv2(category_lv1.id).respond_to?("each")
								- find_categories_lv2(category_lv1.id).each do |category_lv2|			
									%option{ :value => category_lv2.id }= " => #{category_lv2.name}"
			

		.form-group			
			= f.label :sale_off, class: "control-label col-sm-2"
			.col-sm-10				
				= f.text_field :sale_off, :class => "form-control", placeholder: "Enter sale off value"

		.form-group
			= f.label "Sale off type", :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :sale_off_type, "(none)", :checked => @product.sale_off_type == "(none)"
					(None)
						
				%label.radio-inline
					= f.radio_button :sale_off_type, "%", :checked => @product.sale_off_type == "%"
					= "%"

				%label.radio-inline
					= f.radio_button :sale_off_type, "vnd", :checked => @product.sale_off_type == "vnd"
					vnd

		
		.form-group
			= f.label :description, :class => "control-label col-sm-2"
			.col-sm-10				
				= f.text_area :description, :class => "form-control"


		.form-group
			= f.label :status, :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :status, "inactive", :checked => @product.status == "inactive"
					Inactive
						
				%label.radio-inline
					= f.radio_button :status, "active", :checked => @product.status == "active"
					Active

				%label.radio-inline
					= f.radio_button :status, "pending", :checked => @product.status == "pending"
					Pending					
			
				%label.radio-inline
					= f.radio_button :status, "banned", :checked => @product.status == "banned"
					Banned
			
		.form-group
			.col-sm-offset-2.col-sm-2
				= f.submit "Save change", :class => "btn btn-default"
					
			.col-sm-8
				= link_to "Cancel", admin_products_path, :class => "btn btn-default"

app/views/admin/products/index.html.haml
= render "admin/shared/header"
.container-fluid
	%h1 Admin::Products#index
	.row
		.col-md-1
			ID
		.col-md-1
			Image
		.col-md-2
			Name
		.col-md-1
			Price
		.col-md-1
			Banner type
		.col-md-1
			Sale off 
		.col-md-1
			Sold/Total
		.col-md-1
			Status
		.col-md-1
			Category_id
		.col-md-2
			= link_to "Add new Product", new_admin_product_path

	- @products.each do |product|
		.row
			.col-md-1
				= product.id
			.col-md-1
				= image_tag product.images_url, size: "70x70"
			.col-md-2
				= product.name
			.col-md-1
				= money_format(product.price)
			.col-md-1
				= product.banner
			.col-md-1
				= product.sale_off.to_s + product.sale_off_type.to_s
			.col-md-1
				= product.sold.to_s + "/" + product.total.to_s			
			.col-md-1
				= product.status
			.col-md-1
				= show_category_parent(product.category_id)
			.col-md-2
				= link_to "Show", admin_product_path(product)
				%span 
					= "|"
				= link_to "Edit", edit_admin_product_path(product)
				%span 
					= "|"
				= link_to "Delete", admin_product_path(product), method: :delete, data: {confirm: "Are you sure?"}
	= paginate @products

	%br
	= link_to "<< Dashboard", admin_dashboard_index_path

app/views/admin/products/new.html.haml
= render "admin/shared/header"
.container	
	= form_for :product, html: {class: "form-horizontal"}, url: admin_products_path, method: :post do |f|
		.form-group
			= f.label :name, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :name, :class => "form-control", :placeholder => "Enter product name"
			

		.form-group
			= f.label :images, :class => "control-label col-sm-2"
			.col-sm-10				
				= f.file_field :images, :class => "form-control"
		.form-group
			= f.label "Banner type", :class => "control-label col-sm-2"
			.col-sm-10				
				%label.radio-inline
					= f.radio_button :baner, "single", :checked => true
					single
						
				%label.radio-inline
					= f.radio_button :baner, "double", :checked => false
					double
			
		.form-group		
			= f.label :price, :class => "control-label col-sm-2"
			.col-sm-10 				
				= f.text_field :price, :class => "form-control", :placeholder => "Enter price"
			
		.form-group
			= f.label "Number of Total", :class => "control-label col-sm-2"
			.col-sm-10				
				= f.text_field :total, :class => "form-control", :placeholder => "Enter number of total"
			
		.form-group
			= f.label :category_id, :class => "control-label col-sm-2"
			.col-sm-10				
				%select{ :name => 'product[category_id]' }
					-if @categories_lv1.respond_to?("each")
						- @categories_lv1.each do |category_lv1|
							%option{ :value => category_lv1.id }= "#{category_lv1.name}"	
							- if find_categories_lv2(category_lv1.id).respond_to?("each")
								- find_categories_lv2(category_lv1.id).each do |category_lv2|			
									%option{ :value => category_lv2.id }= " => #{category_lv2.name}"
			

		.form-group			
			= f.label :sale_off, class: "control-label col-sm-2"
			.col-sm-10				
				= f.text_field :sale_off, :class => "form-control", placeholder: "Enter sale off value"

		.form-group
			= f.label "Sale off type", :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :sale_off_type, "(none)", :checked => true
					(None)
						
				%label.radio-inline
					= f.radio_button :sale_off_type, "%", :checked => false
					= "%"

				%label.radio-inline
					= f.radio_button :sale_off_type, "vnd", :checked => false
					vnd

		
		.form-group
			= f.label :description, :class => "control-label col-sm-2"
			.col-sm-10				
				= f.text_area :description, :class => "form-control"


		.form-group
			= f.label :status, :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :status, "inactive", :checked => true
					Inactive
						
				%label.radio-inline
					= f.radio_button :status, "active", :checked => false
					Active

				%label.radio-inline
					= f.radio_button :status, "pending", :checked => false
					Pending					
			
				%label.radio-inline
					= f.radio_button :status, "banned", :checked => false
					Banned
			
		.form-group
			.col-sm-offset-2.col-sm-2
				= f.submit "Create new Product", :class => "btn btn-default"
					
			.col-sm-8
				= link_to "Cancel", admin_products_path, :class => "btn btn-default"

app/views/admin/products/show.html.haml
= render "admin/shared/header"
.container	
	.pull-left
		= image_tag @product.images_url, :class => "img-rounded", size: "128x128"
	.pull-left
		.row
			.col-lg-offset-1.col-lg-4
				Name:
			.col-lg-6
				= @product.name

		.row
			.col-lg-offset-1.col-lg-4
				Price:
			.col-lg-6
				= money_format(@product.price)

		.row
			.col-lg-offset-1.col-lg-4
				Sale off:
			.col-lg-6
				= @product.sale_off.to_s + @product.sale_off_type.to_s

		.row
			.col-lg-offset-1.col-lg-4
				Created by:
			.col-lg-6
				= @product.user.try(:email)

		.row
			.col-lg-offset-1.col-lg-4
				Banner type:
			.col-lg-6
				= @product.banner

		.row
			.col-lg-offset-1.col-lg-4
				Create at:
			.col-lg-6
				= @product.created_at
		.row
			.col-lg-offset-1.col-lg-4
				Update at:
			.col-lg-6
				= @product.updated_at
		.row
			.col-lg-offset-1.col-lg-4
				Status:
			.col-lg-6
				= @product.status

	.clearfix
	= link_to "Add new Product", new_admin_product_path
	%br
	= link_to "Back", admin_products_path