config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions:       'users/sessions'
  }

  namespace :admin do
    resources :products, :users, :categories
    get 'dashboard/index'
  end

  match 'users/index', to: 'users/users#index', via: [:get]

  resources :cart, only: [:index] do
    collection do
      get 'add_to_cart'
      get 'update_quantity_to_cart'
      get 'delete_product_to_cart'
    end
  end

    
end

app/models/category.rb
class Category < ActiveRecord::Base
	 paginates_per(20)
	 belongs_to :user
	 has_many :products
	 has_many :children, class_name: "Category",
                          foreign_key: "parent_id"
 
	 belongs_to :parent, class_name: "Category"
	 # def parent
	 # 	self.parent_id == 0 ? nil : Category.where(id: self.parent_id ).first
	 # end

	 # def children
	 # 	Category.where(parent_id: self.id )#.first
	 # end

	 def self.policy_class
	    Admin::CategoryPolicy
	 end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_authorize, only: [:show, :edit, :update, :destroy]
  def index
    authorize Category
  	@categories = Category.all.order(parent_id: :ASC).page params[:page]
  end

  def show
    
  end

  def new
  	@category = Category.new
    authorize @category
  	@categories_parent = Category.where(parent_id: "0")
  	@i = 0
  end

  def edit
  	@i = 0  	
  	@categories_parent = Category.where(parent_id: "0").order("id = #{@category.parent_id} DESC")
  end

  def create
  	@category = current_user.categories.new(category_params)
    authorize @category
  	if @category.save
      flash[:success] = "create new category success!"
  		redirect_to admin_category_path(@category)
  	else
      flash[:error] = "Fail! Please try again!"
  		render :new
  	end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Uppdate success!"
      redirect_to admin_category_path(@category)
    else
      flash[:error] = "Fail! Please try again!"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = "Uppdate success!"
    else
      flash[:error] = "Fail! Please try again!"
    end

    redirect_to admin_categories_path
  end

  private

  def check_authorize
    @category = Category.find(params[:id])
    authorize @category
  end
  def category_params
  	params.require(:category).permit(:name, :parent_id, :description, :status, :order)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def show
  	@category = Category.find(params[:id])
  	@category_children = @category.children
  	@categories_other = Category.where(:parent_id => '0', :status => "active").where.not(:id => params[:id]).order(order: :ASC)
  	
  	@products = Product.where("category_id in (?)", @category.children.map(&:id) << @category.id ).where(:status => "active")
   
  	@product_slideshow_single = Product.where(:banner => "single", :status => "active").order(sold: :DESC).limit(4)
  	@product_slideshow_double = Product.where(:banner => "double", :status => "active").order(sold: :DESC).limit(4)

  	@product_slideshow = []
  	@product_slideshow_double.each_with_index do |product, index|
  		@product_slideshow << product

  		@product_slideshow_single.each_with_index do |product2, index2|
  			if index == index2
  				@product_slideshow << product2
	  			break
	  		end
	  	end
  	end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
	def show_category_parent(id)
		@string = id.to_s
		return @string += " (none)" if id == 0
		
	  	@category = Category.find(id)		  	
		return @string += " (" + @category.name.to_s + ")" if @category.respond_to?("name")
	end

	def show_category_name(id)
		return @string += "(none)" if id == 0		
	  	@category = Category.find(id)
	  	@category.name
	end

	def find_categories_lv2(id)
		return false if id == 0
		@categories_lv2 = Category.where(:parent_id => "#{id}")
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div class="container-fluid background-wall">
	<div class="container">
		<div class="panel panel-default noborder-radius panel-default-custom">
			<div class="panel-body panel-cutom">
				<%= link_to "Trang chủ", root_path, :class => "text-muted" %>
				<% if @category.parent %>
					<i> >> </i>
				  	<%= link_to @category.parent.name, category_path(@category.parent), :class => "text-muted" %>
				<% end %>
			  	<i> >> </i>
			  	<%= link_to @category.name, category_path(@category), :class => "text-muted" %>
			</div>
		</div>

		<div class="">
			<div class="pull-left" style="width: 230px;">
				<div class="panel panel-default">
					<div class="panel-heading panel-body white" >
						<i class="glyphicon glyphicon-film pull-left">&nbsp</i>
					  	<a href="#" >
					  		<%= link_to @category.name, category_path(@category), :class => "text-danger" %>
					  	</a>
						<div class=" col-sm-12">
							<% if @category_children.respond_to?("each") %>
								<% @category_children.each do |category| %>
									...<%= link_to category.name, category_path(category), :class => "text-muted" %><br>
								<% end %>
							<% end %>
						</div>
					</div>
				
					<div class="panel-body">
					  	<em class="text-muted">Chuyển danh mục khác:</em>
						<div class=" col-md-12">
							
							<% if @categories_other.respond_to?("each") %>
								<% @categories_other.each do |category| %>
									<i class="glyphicon glyphicon-minus" style="font-size: 10px;"></i>
									<%= link_to category.name, category_path(category), :class => "text-info" %><br>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>		
							
			</div>
					
			
			<div class="pull-left" style="width: 910px;">
				<div class=""></div>
				<div class="slide-show">
					<div id="myCarousel6" class="carousel slide carousel6" data-ride="carousel">
						<!-- Indicators -->
						<div class="pull-left" style="margin-left: 14.5px;">NỔI BẬT!</div>

						<ol class="carousel-indicators nomargin carousel-indicators-custom">
							<li data-target="#myCarousel6" data-slide-to="0" class="active"></li>
							<li data-target="#myCarousel6" data-slide-to="1"></li>
							<li data-target="#myCarousel6" data-slide-to="2"></li>
							<li data-target="#myCarousel6" data-slide-to="3"></li>
						</ol>
						<!-- Wrapper for slides -->
						<div class="carousel-inner" role="listbox">

							<% @product_slideshow.each_with_index do |product, index| %>
								<% if index%2 == 0 %>
									<div class="item <%= 'active' if index == 0 %>">
								<% end %>
									<div class="<%= product.banner == 'double' ? 'col-md-8' : 'col-md-4' %>">
										<div class="thumbnail noborder-radius">
											<%= image_tag product.images_url, :class => "img-thumnail" %>
											<div class="caption">
												<div class="product-name-div">
											    	<div class="nomargin <%= product.banner == 'double' ? 'h2 product-name-div' : 'h3' %>">
											    		<small><%= product.name %></small>
											    	</div>												
												</div>
										    	<code><%= price_now(product.price, product.sale_off, product.sale_off_type) %></code> <del class="text-muted"><%= money_format(product.price) unless product.sale_off_type == "(none)" %></del>
										    	<div class="">
										      		<small class="text-muted"><%= product.sold %> đã mua</small>
										      		<i class="glyphicon glyphicon-circle-arrow-right pull-right"></i>
										    	</div>
											</div>
											<i class="glyphicon glyphicon-certificate glyphicon-certificate-sm"></i>
											<span class="sale-off-val">-25%</span>
										</div>
									</div>
								<% if index%2 != 0 %>
									</div>
								<% end %>
							<% end %>							
												
						</div>

					</div>
				</div>

				
				<div class="content">
					<div class="">
						<div class="pull-left">Có <%= @products.count %> deals <strong><%= @category.name %></strong>!</div>
						<div class="pull-right">
							<span class="text-muted"> Sắp xếp theo </span>
							<div class="btn-group">
								<button class="btn btn-default btn-xs dropdown-toggle noborder-radius" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 32px; width: 158px; border: none;">
									Bán chạy nhất 
									<span class="caret"></span> 
								</button> 
								<ul class="dropdown-menu nopadding nomargin noborder-radius">
									<li><a href="#">Mới nhất</a></li>
									<li><a href="#">Nổi bật</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>

					<% @products.each do | product | %>
					<div class="<%= product.banner == 'double' ? 'col-md-8' : 'col-md-4' %>">
						<div class="thumbnail noborder-radius">
							<%= link_to product_path(product) do %>
								<%= image_tag product.images_url, :class => "img-thumnail" %>
								<div class="caption">								
							    	<div class="nomargin <%= product.banner == 'double' ? 'h2 product-name-div' : 'h3' %>">
							    		<small><%= product.name %></small>
							    	</div>	

							    	<code><%= price_now(product.price, product.sale_off, product.sale_off_type) %></code> <del class="text-muted"><%= money_format(product.price) unless product.sale_off_type == "(none)" %></del>

							    	<div class="">
							      		<small class="text-muted"><%= product.sold %> đã mua</small>
							      		<i class="glyphicon glyphicon-circle-arrow-right pull-right"></i>
							    	</div>
								</div>
								<i class="glyphicon glyphicon-certificate glyphicon-certificate-sm"></i>
								<span class="sale-off-val">-25%</span>
							<% end %>
						</div>
					</div>
					<% end %>

					
				</div>
				<div class="clearfix"></div>
				<div class="panel panel-default noborder-radius">
					<div class="panel-body">
				    	Có thể bạn quan tâm
				    	<div id="myCarousel5" class="carousel slide" data-ride="carousel">
							<!-- Wrapper for slides -->
							<div class="carousel-inner tab-carousel-inner" role="listbox">
								<div class="item active">
									<ul class="list-inline">
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>	
									</ul>
								</div>

								<div class="item content-panel">
									<ul class="list-inline">
										
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
										<li class="margin-left-right-20">
											<img src="https://muachungcdn.com/thumb_w/220,80/product/173/10/hyd7l.jpg" alt="Chania" width="140px" height="140px">
											<div class="lead text-muted">thong tin sp</div>
											<div class="">gia</div>						
										</li>
															
									</ul>
								</div>
							</div>
							<!-- Left and right controls -->
							<a class="left btn btn-default button-left-tab" href="#myCarousel5" role="button" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
							</a>
							<a class="right btn btn-default button-right-tab" href="#myCarousel5" role="button" data-slide="next">
								<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</a>
						</div>	
					</div>
				</div>
			</div>
		</div>
	</div>
</div>