config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions:       'users/sessions'
  }

  namespace :admin do
    resources :products, :users, :categories
    get 'dashboard/index'
  end

  match 'users/index', to: 'users/users#index', via: [:get]

  resources :cart, only: [:index] do
    collection do
      get 'add_to_cart'
      get 'update_quantity_to_cart'
      get 'delete_product_to_cart'
    end
  end

    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
  has_many :categories

  paginates_per(10)
  
  def self.policy_class
    Admin::UserPolicy
  end

  def admin?
  	role == "admin"
  end

  def support?
  	role == "aupport"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_authorize, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all.page params[:page]
  	authorize User
  end

  def show
  	
  end

  def new
  	@user = User.new
    authorize @user
  end

  def edit
  end

  def create
  	@user = User.new(user_params)
  	authorize @user
  	if @user.save
      flash[:success] = "Create new User success!"
  		redirect_to admin_user_path(@user)
  	else
      flash[:error] = "Fail! Please try again!"
  		render :new
  	end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Uppdate success!"
      redirect_to admin_user_path(@user)
    else
      flash[:error] = "Fail! Please try again!"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Uppdate success!"
    else
      flash[:error] = "Fail! Please try again!"
    end

    redirect_to admin_users_path
  end

  private

  def check_authorize
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
  	params.require(:user).permit(:email, :role, :fullname, :password)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    "/users/index"    
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # The path used after sign up.
  def after_sign_in_path_for(resource)
    "/users/index"    
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def index
  	@user = current_user
  	#respond_to do |format|
	#    format.html  # index.html.erb
	#    format.json  { render :json => @user }
	#    format.js 
	#  end 
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admin/users/edit.html.haml
= render "admin/shared/header"
.container	
	=form_for :user, html: {class: "form-horizontal"}, url: admin_user_path, method: :path do |f|
		.form-group
			= f.label :email, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :email, :class => "form-control", :placeholder => "Enter email"
					
		.form-group
			= f.label :fullname, :class => "control-label col-sm-2"
			.col-sm-10
				=f.text_field :fullname, :class => "form-control"

		.form-group
			= f.label :role, :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :role, "Member", :checked => @user.role == "Member"
					Member
						
				%label.radio-inline
					= f.radio_button :role, "Support", :checked => @user.role == "Support"
					Support
					
			
				%label.radio-inline
					= f.radio_button :role, "Admin", :checked => @user.role == "Admin"
					Admin
							
		.form-group
			.col-sm-offset-2.col-sm-2
				= f.submit "Save change", :class => "btn btn-default"

		
			.col-sm-6
				= link_to "Cancel", admin_users_path, :class => "btn btn-default"

app/views/admin/users/index.html.haml
= render "admin/shared/header"
.container
	%h1 User#index

	.row
		.col-sm-1
			ID
		.col-sm-2
			Fullname
		.col-sm-3
			Email
		.col-sm-3 
			Role
		.col-sm-3
			= link_to "Add new User", new_admin_user_path

		- @users.each do |user|
			.col-sm-1
				= user.id
			.col-sm-2
				= user.fullname
			.col-sm-3
				= user.email
			.col-sm-3 
				= user.role
			.col-sm-3
				= link_to "Show", admin_user_path(user)
				= link_to "Edit", edit_admin_user_path(user)
				= link_to "Delete", admin_user_path(user), method: :delete, data: {confirm: "Are you sure?"}
	= paginate @users

	%br
	= link_to "<< Dashboard", admin_dashboard_index_path

app/views/admin/users/new.html.haml
= render "admin/shared/header"
.container	
	=form_for :user, html: {class: "form-horizontal"}, url: admin_users_path, method: :post do |f|
		.form-group
			= f.label :email, :class => "control-label col-sm-2"
			.col-sm-10
				= f.text_field :email, :class => "form-control", :placeholder => "Enter email"
					
		.form-group
			
			= f.label :password, :class => "control-label col-sm-2"
			.col-sm-10
				
				= f.password_field :password, :class => "form-control", :placeholder => "Enter password"

		.form-group
			
			=f.label :password_confirm, :class => "control-label col-sm-2"
			.col-sm-10
				
				= f.password_field :password_confirm, :class => "form-control", :placeholder => "Enter password"

		.form-group
			= f.label :fullname, :class => "control-label col-sm-2"
			.col-sm-10
				=f.text_field :fullname, :class => "form-control"

		.form-group
			= f.label :role, :class => "control-label col-sm-2"
			.col-sm-10
				
				%label.radio-inline
					= f.radio_button :role, "Member", :checked => true
					Member
						
				%label.radio-inline
					= f.radio_button :role, "Support", :checked => false
					Support
					
			
				%label.radio-inline
					= f.radio_button :role, "Admin", :checked => false
					Admin
							
		.form-group
			.col-sm-offset-2.col-sm-10
				= f.submit :submit, :class => "btn btn-default"
	

app/views/admin/users/show.html.haml
= render "admin/shared/header"
.container
	.row
		.col-md-3
			Email:
		.col-md-9
			= @user.email
		.col-md-3
			Fullname:
		.col-md-9
			= @user.fullname.capitalize
		.col-md-3
			Role:
		.col-md-9
			= @user.role
	= link_to "Add new User", new_admin_user_path
	%br
	= link_to "Back", admin_users_path